// This file is automatically generated. Do not edit it directly.
import { createClient, REALTIME_CHANNEL_STATES } from '@supabase/supabase-js';
import type { RealtimeChannel, RealtimeChannelSendResponse } from '@supabase/supabase-js';
import type { Database } from './types';

type StorageLike = Pick<Storage, 'getItem' | 'setItem' | 'removeItem' | 'clear'>;

const createMemoryStorage = (): StorageLike => {
  const store = new Map<string, string>();

  return {
    getItem: (key: string) => (store.has(key) ? store.get(key)! : null),
    setItem: (key: string, value: string) => {
      store.set(key, value);
    },
    removeItem: (key: string) => {
      store.delete(key);
    },
    clear: () => {
      store.clear();
    },
  };
};

const storage: StorageLike | undefined =
  typeof window !== 'undefined' && 'localStorage' in window
    ? window.localStorage
    : createMemoryStorage();

const importMetaEnv = (() => {
  try {
    return new Function(
      'return typeof import.meta !== "undefined" ? import.meta.env : undefined;',
    )() as Record<string, string> | undefined;
  } catch {
    return undefined;
  }
})();
const processEnv = typeof process !== 'undefined' ? process.env : undefined;

const SUPABASE_URL = importMetaEnv?.VITE_SUPABASE_URL ?? processEnv?.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  importMetaEnv?.VITE_SUPABASE_PUBLISHABLE_KEY ?? processEnv?.VITE_SUPABASE_PUBLISHABLE_KEY;

const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const createFallbackChannel = (): RealtimeChannel => {
  const channel: Partial<RealtimeChannel> & { state: RealtimeChannel['state'] } = {
    state: REALTIME_CHANNEL_STATES.closed,
    on: () => channel as RealtimeChannel,
    subscribe: () => channel as RealtimeChannel,
    send: async (): Promise<RealtimeChannelSendResponse> => 'ok' as any,
    track: async (): Promise<RealtimeChannelSendResponse> => 'ok' as any,
    presenceState: () => ({}),
    unsubscribe: async (): Promise<'ok' | 'timed out' | 'error'> => 'ok',
  };

  return channel as RealtimeChannel;
};

const createSupabaseFallback = () => {
  const subscription = { unsubscribe: () => {} };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription }, error: null }),
      signInAnonymously: async () => ({ data: null, error: null }),
    },
    channel: () => createFallbackChannel(),
    __isFallback: true,
  } as const;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = (isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : (createSupabaseFallback() as unknown)) as ReturnType<typeof createClient<Database>> & {
  __isFallback?: boolean;
};

export const isSupabaseFallback = !isSupabaseConfigured;
